FROM python:3.10-slim

WORKDIR /app

COPY req.txt .
RUN pip install --no-cache-dir --upgrade -r /app/req.txt

COPY ./app/ .

#CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]